config/routes.rb
Medmanage::Application.routes.draw do

  resources :patients
  resources :allergies
  resources :drugs
  resources :medications

  
  match '/drugs/:id/manage_interactions', :to => 'drugs#manage_interactions', :as => 'manage_interactions', :via => 'post'
  match '/drugs/:id/manage_interactions_update', :to => 'drugs#manage_interactions_update', :as => 'manage_interactions_update', :via => 'post'

  root :to => 'home#index'

end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  
  belongs_to :patient
  
  validates_presence_of :name, :kind, :patient_id

end

app/models/drug.rb
class Drug < ActiveRecord::Base
  
  TYPES = ['Analgesic', 'Antacid', 'Anti-Coagulant', 'Anti-Convulsant', 'Anti-Depressant', 'Anti-Diarrheal', 'Anti-Fungal', 'Anti-Histamine', 'Anti-Psychotic', 'Anti-Viral', 'Antibiotic', 'Bronchodilator', 'Decongestant', 'Diuretic', 'Heparin', 'Hormone', 'Laxitive', 'Leprostatic', 'Muscle Relaxant', 'Nitrate', 'Sedative', 'Statin', 'Steroid', 'Vasoconstictor', 'Vasodilator']

  validates_presence_of :name, :kind, :code, :purpose
  validates_uniqueness_of :interactions
  
  serialize :interactions
  
  def self.interacts_with(drugs)
    kinds = []
    @interactions = []
    drugs.each do |drug|
      kinds << drug.kind
    end
    #puts kinds
    drugs.each do |drug|
      drug.interactions.each do |interaction|
        if kinds.include?(interaction)
          #puts "#{drug.name} has an interaction with another assigned prescription"
          @interactions << "Warning!  #{drug.name} may have an interaction with another assigned prescription!"
        end
      end
    end
    return @interactions
  end
  
  def self.allergies_to(drugs, allergies)
    allergy_kinds = []
    @allergic = []
    allergies.each do |allergy|
      allergy_kinds << allergy.kind
    end
    #puts allergy_kinds
    drugs.each do |drug|
      if allergy_kinds.include?(drug.kind)
        #puts "Warning!  The patient may be allergic to #{drug.name}!"
        @allergic << "Warning!  The patient may be allergic to #{drug.name}!"
      end
    end
    return @allergic
  end
  
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :patient
  belongs_to :drug
  
  validates_presence_of :patient_id, :drug_id, :prescribing, :prescription, :dose, :quantity, :filled_on, :refills
  validates_uniqueness_of :prescription
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  
  SEX = ['Male', 'Female', 'Neither o.O']
  
  has_many :allergies, :dependent => :destroy
  has_many :medications, :dependent => :destroy
  has_many :drugs, :through => :medications
  
  validates_presence_of :last_name, :first_name, :dob, :sex, :ssn, :insurance, :primary
  validates_uniqueness_of :ssn
  
  # topup
  
end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController
  
  respond_to :html, :json
  
  def new
    @allergy = Allergy.new
    @allergy.patient_id = params[:patient_id]

    respond_with @allergy
  end
  
  def create
    @allergy = Allergy.new(params[:allergy])

    if @allergy.save
      flash[:notice] = "Successfully added patient's allergy."
      respond_with @allergy, :location => patient_path(Patient.where("id = ?", @allergy.patient_id).first)
    else
      flash[:alert] = "Failed to add allergy to user."
      render :action => :new
    end
  end
  
  def destroy
    @allergy = Allergy.find(params[:id])
    flash[:alert] = "Successfully removed allergy." if @allergy.delete
    respond_with @allergy, :location => patient_path(Patient.where("id = ?", @allergy.patient_id).first)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  
  respond_to :html, :json
  
  before_filter :find_drug, :except => ['index', 'new', 'create']
  
  def index
    @drugs = Drug.all
  end
  
  def show
    respond_with @drug
  end
  
  def new
    @drug = Drug.new
    respond_with @drug
  end
  
  def create
    @drug = Drug.new(params[:drug])
    if @drug.save
      flash[:notice] = "Successfully created drug record."
      respond_with @drug
    else
      flash[:alert] = "Failed to create drug record."
      render :action => :new
    end
  end
  
  def edit
    respond_with @drug
  end
  
  def update
    if @drug.update_attributes(params[:drug])
      flash[:notice] = "Successfully modified drug record."
      respond_with @drug, :location => drugs_path
    else
      flash[:alert] = "Failed to update drug record."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:alert] = "Successfully removed drug from database." if @drug.delete
    respond_with @drug
  end
  
  def manage_interactions
    
  end
  
  def manage_interactions_update
    params[:drug] ||= {"interactions"=>[""]}
    puts params[:drug]
    if @drug.update_attributes(params[:drug])
      flash[:notice] = "Successfully modified interactions."
      respond_with @drug
    else
      flash[:alert] = "Failed to modify interactions."
      render :action => :manage_interactions
    end
  end
  
  private
  
  def find_drug
    @drug = Drug.find(params[:id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  
  respond_to :html, :json
  
  before_filter :find_medication, :except => ['new', 'create']
  
  def new
    @medication = Medication.new
    @medication.patient_id = params[:patient_id]
    
    respond_with @medication
  end
  
  def create
    @medication = Medication.new(params[:medication])
    if @medication.save
      flash[:notice] = "Successfully created prescription."
      respond_with @medication, :location => patient_path(Patient.where("id = ?", @medication.patient_id).first)
    else
      flash[:alert] = "Failed to create prescription."
      render :action => :new
    end
  end
  
  def edit
    respond_with @medication
  end
  
  def update
    if @medication.update_attributes(params[:medication])
      flash[:notice] = "Successfully modified prescription information."
      respond_with @medication, :location => patient_path(Patient.where("id = ?", @medication.patient_id).first)
    else
      flash[:alert] = "Failed to update prescription information."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:alert] = "Successfully removed prescription information." if @medication.delete
    respond_with @medication, :location => patient_path(Patient.where("id = ?", @medication.patient_id).first)
  end
  
  private
  
  def find_medication
    @medication = Medication.find(params[:id])
  end
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  
  respond_to :html, :json
  
  before_filter :find_patient, :except => ['index', 'new', 'create']
  
  def index
    @patients = Patient.all
  end
  
  def show
    @drugs = @patient.drugs
    @interactions = @patient.drugs.interacts_with(@patient.drugs)
    #puts @interactions
    @allergic = @patient.drugs.allergies_to(@patient.drugs, @patient.allergies)
    #puts @allergic
    respond_with @patient

  end
  
  def new
    @patient = Patient.new
    respond_with @patient
  end
  
  def create
    @patient = Patient.new(params[:patient])
    if @patient.save
      flash[:notice] = "Successfully created patient record."
      respond_with @patient, :location => patient_path(@patient)
    else
      flash[:alert] = "Failed to create patient record."
      render :action => :new
    end
  end
  
  def edit
    respond_with @patient
  end
  
  def update
    if @patient.update_attributes(params[:patient])
      flash[:notice] = "Successfully modified patient record."
      respond_with @patient, :location => patient_path(@patient)
    else
      flash[:alert] = "Failed to update patient record."
      render :action => :edit
    end
  end
  
  def destroy
    flash[:alert] = "Successfully removed patient record." if @patient.delete
    respond_with @patient
  end
  
  private
  
  def find_patient
    @patient = Patient.find(params[:id])
  end
  
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/allergies/_form.html.haml
= form_for @allergy do |f|
  = f.error_messages
  %fieldset
    %legend
      Information
    %p
      = f.label :name
      %br
      = f.text_field :name
    %p
      = f.label :kind
      %br
      =f.select :kind, Drug::TYPES
    = f.hidden_field :patient_id
  %p
    = f.submit
    = "/"
    %a.cancel_link{ :href => patient_path(Patient.find(params[:patient_id])) } Cancel

app/views/allergies/new.html.haml
= render :partial => 'form'

app/views/drugs/_drug.html.haml
%li
  = link_to "#{drug.name}", drug_path(drug)

app/views/drugs/_form.html.haml
= form_for @drug do |f|
  = f.error_messages
  %fieldset
    %legend
      Information
    %p
      = f.label :name
      %br
      = f.text_field :name
    %p
      = f.label :kind, "Classification"
      %br
      = f.select :kind, Drug::TYPES
    %p
      = f.label :code
      %br
      = f.text_field :code
    %p
      = f.label :generic_for
      %br
      = f.text_field :generic_for
    %p
      = f.label :purpose
      %br
      = f.text_field :purpose
  %p
    = f.submit
    or
    %a.cancel_link{ :href => drugs_path } Cancel

app/views/drugs/edit.html.haml
%h3
  = "Edit #{@drug.name}'s Data"

= render :partial => 'form'

app/views/drugs/index.html.haml
%h3
  Drugs Index

%ul.nostyle
  = render :partial => 'drug', :collection => @drugs

%p
  = link_to "Add drug to the database", new_drug_path
  %br
  = link_to "Home", root_path

app/views/drugs/manage_interactions.html.haml
= form_tag manage_interactions_update_path(@drug), :method => :post do  
  %fieldset
    %legend
      Drug Interactions
    - Drug::TYPES.each do |type|
      %p
        = type
        %br
        = check_box_tag "drug[interactions][]", type, @drug.interactions.include?(type)
    %p
      = submit_tag
      = "/"
      %a.cancel_link{ :href => drug_path(@drug) } Cancel

app/views/drugs/new.html.haml
%h3
  Create a New Drug Entry

= render :partial => 'form'

app/views/drugs/show.html.haml
%ul.nostyle.nomargin
  %li
    = "Name:  #{@drug.name}"
  %li
    = "Code:  #{@drug.code}"
  %li
    = "Classification:  #{@drug.kind}"
  %li
    = "Generic for:  #{@drug.generic_for}"
  %li
    = "Purpose:  #{@drug.purpose}"
  %li
    Interactions:
    %ul.nostyle
      - @drug.interactions.each do |interaction|
        %li
          = interaction
%p
  = link_to "Manage this drug's interactions", manage_interactions_path(@drug), :method => :post
%p
  = link_to "Edit this drug's information", edit_drug_path(@drug)
  %br
  = link_to "Delete this drug from the database", drug_path(@drug), :method => 'delete', :confirm => "Are you sure you want to delete #{@drug.name} from the database?"
  %br
  = link_to "Back", drugs_path

app/views/home/index.html.haml
%h3
  %p
    = link_to "Patient Index", patients_path
    %br
    = link_to "Drug Index", drugs_path
    
%p
  Welcome to the medication management test application.  Please view the readme, accessable at 
  %a{:href => "https://github.com/mdms-scott/medmanage"} https://github.com/mdms-scott/medmanage, 
  for more information and the source code.

app/views/layouts/application.html.haml
!!!
%head
  %title medmanage
  = stylesheet_link_tag :all
  = javascript_include_tag :defaults
  = csrf_meta_tag
%body
  #flash
    #flash_inner
      .notice
        = notice
      .alert
        = alert
    .clear
  #main_container
    = yield

app/views/medications/_form.html.haml
= form_for @medication do |f|
  %fieldset
    %legend
      Information
    %p
      = f.label :drug_id
      %br
      = f.select :drug_id, Drug.all.collect {|d| [ d.name, d.id ] }, {:prompt => 'Select Drug'}
    %p
      = f.label :prescription, "Prescription Code"
      %br
      = f.number_field :prescription
    %p
      = f.label :prescribing, "Prescribing Physician"
      %br
      = f.text_field :prescribing
    %p
      = f.label :dose, "Dose (in mg)"
      %br
      = f.number_field :dose
    %p
      = f.label :quantity
      %br
      = f.number_field :quantity
    %p
      = f.label :refills
      %br
      = f.number_field :refills
    %p
      = f.label :filled_on, "Last Filled on"
      %br
      = f.date_select :filled_on, {:use_month_numbers => true, :end_year => Time.now.year, :order => [:month, :day, :year]}
    %p
      = f.hidden_field :patient_id
  %p
    = f.submit
    = "/"
    %a.cancel_link{ :href => patient_path(Patient.where("id = ?", @medication.patient_id).first) } Cancel

app/views/medications/edit.html.haml
%h3
  Edit Prescription Information

= render :partial => 'form'

app/views/medications/new.html.haml
%h3
  Add a New Prescription

= render :partial => 'form'

app/views/patients/_form.html.haml
= form_for @patient do |f|
  =f.error_messages
  %fieldset
    %legend
      Information
    #form_left
      %p
        = f.label :last_name
        %br
        = f.text_field :last_name
      %p
        = f.label :middle_name
        %br
        = f.text_field :middle_name
      %p
        = f.label :dob, "Date of Birth"
        %br
        = f.date_select :dob, {:use_month_numbers => true, :start_year => Time.now.year - 120, :order => [:month, :day, :year]}
      %p
        = f.label :attending, "Attending Physician"
        %br
        = f.text_field :attending
      %p
        = f.label :insurance, "Insurance Provider"
        %br
        = f.text_field :insurance
    #form_right
      %p
        = f.label :first_name
        %br
        = f.text_field :first_name
      %p
        = f.label :ssn, "SSN"
        %br
        = f.number_field :ssn
      %p
        = f.label :sex
        %br
        = f.select :sex, Patient::SEX
      %p
        = f.label :primary, "Primary Care Physician"
        %br
        = f.text_field :primary
    .clear
  %p
    = f.submit
    or
    %a.cancel_link{ :href => patients_path } Cancel

app/views/patients/_patient.html.haml
%tr
  %td
    = link_to "#{patient.last_name}, #{patient.first_name} #{patient.middle_name}", patient_path(patient)
  %td
    = patient.id
  %td
    = patient.updated_at

app/views/patients/edit.html.haml
%h3
  = "Editing #{@patient.first_name}'s Data"
  
= render :partial => 'form'

app/views/patients/index.html.haml
%h3
  Patients Index

%table
  %tr
    %th
      Name
    %th
      Patient ID
    %th
      Last Modified On
  = render :partial => 'patient', :collection => @patients

%p
  = link_to "Create a New Patient Record", new_patient_path
  %br
  = link_to "Home", root_path

app/views/patients/info/_allergic_reactions.html.haml
- @allergic.each do |allergic|
  %p
    = allergic

app/views/patients/info/_drug_interactions.html.haml
- @interactions.each do |interaction|
  %p
    = interaction

app/views/patients/info/_patient_allergies.html.haml
%table
  %tr
    %th
      Allergy
    %th
      Classification
    %th
      Actions
  - @patient.allergies.each do |allergy|
    %tr
      %td
        = allergy.name
      %td
        = allergy.kind
      %td
        = link_to "Delete", allergy_path(allergy), :method => 'delete', :confirm => "Are you sure you want to delete this allergy?"

= link_to "Add a new allergy", new_allergy_path(:patient_id => @patient.id)

app/views/patients/info/_patient_info.html.haml
%ul.nostyle.nomargin
  %li
    = "Name:  #{@patient.first_name} #{@patient.middle_name} #{@patient.last_name}"
  %li
    = "SSN:  #{@patient.ssn}"
  %li
    = "Date of Birth:  #{@patient.dob.strftime('%B %d, %Y')}"
  %li
    = "Sex:  #{@patient.sex}"
  %li
    = "Insurance Provider:  #{@patient.insurance}"
  %li
    = "Primary Care Physician:  #{@patient.primary}"
  %li
    = "Current Attending Physician:  #{@patient.attending}"
%p
  = link_to "Edit this patient's information", edit_patient_path(@patient)

app/views/patients/info/_patient_medications.html.haml
%table
  %tr
    %th
      Drug
    %th
      Prescription Code
    %th
      Prescribing Physician
    %th
      Dose (in mg)
    %th
      Quantity
    %th
      Refills Remaining
    %th
      Last Filled On
    %th
      Actions
  - @patient.medications.each do |medication|
    %tr
      %td
        = link_to "#{medication.drug.name}", drug_path(medication.drug)
      %td
        = medication.prescription
      %td
        = medication.prescribing
      %td
        = medication.dose
      %td
        = medication.quantity
      %td
        = medication.refills
      %td
        = medication.filled_on.strftime('%m %d, %Y')
      %td
        = link_to "Edit", edit_medication_path(medication)
        |
        = link_to "Delete", medication_path(medication), :method => 'delete', :confirm => "Are you sure you want to delete this prescription?"
      

= link_to "Add prescription information", new_medication_path(:patient_id => @patient.id)

app/views/patients/new.html.haml
%h3
  Create a New Patient Record

= render :partial => 'form'

app/views/patients/show.html.haml
%h3
  = "Viewing Patient #{@patient.first_name}'s Information"

#container
  = render :partial => '/patients/info/patient_info'
#container
  = render :partial => '/patients/info/patient_allergies'
#container
  = render :partial => '/patients/info/patient_medications'
- if @allergic.empty?
-else
  #container.alert.allergies
    = render :partial => 'patients/info/allergic_reactions'
- if @interactions.empty?
- else
  #container.alert.interactions
    = render :partial => '/patients/info/drug_interactions'


= link_to "Delete this patient's records", patient_path(@patient), :method => 'delete', :confirm => "Are you sure you want to delete #{@patient.first_name}'s records?"
%br
= link_to "Back to Patients Index", patients_path